/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    EmptyResult: typeof import('./src/components/Result/EmptyResult.vue')['default']
    InfoResult: typeof import('./src/components/Result/InfoResult.vue')['default']
    LoadingResult: typeof import('./src/components/Result/LoadingResult.vue')['default']
    PageLayout: typeof import('./src/components/PageLayout/PageLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubPageLayout: typeof import('./src/components/PageLayout/SubPageLayout.vue')['default']
    SubTitle: typeof import('./src/components/PageLayout/SubTitle.vue')['default']
    SuccessResult: typeof import('./src/components/Result/SuccessResult.vue')['default']
    TAlert: typeof import('tdesign-vue-next')['Alert']
    TAside: typeof import('tdesign-vue-next')['Aside']
    TBackTop: typeof import('tdesign-vue-next')['BackTop']
    TButton: typeof import('tdesign-vue-next')['Button']
    TCard: typeof import('tdesign-vue-next')['Card']
    TCollapse: typeof import('tdesign-vue-next')['Collapse']
    TCollapsePanel: typeof import('tdesign-vue-next')['CollapsePanel']
    TContent: typeof import('tdesign-vue-next')['Content']
    TDivider: typeof import('tdesign-vue-next')['Divider']
    TDropdown: typeof import('tdesign-vue-next')['Dropdown']
    TEmpty: typeof import('tdesign-vue-next')['Empty']
    TForm: typeof import('tdesign-vue-next')['Form']
    TFormItem: typeof import('tdesign-vue-next')['FormItem']
    TInput: typeof import('tdesign-vue-next')['Input']
    TInputNumber: typeof import('tdesign-vue-next')['InputNumber']
    TLayout: typeof import('tdesign-vue-next')['Layout']
    TLoading: typeof import('tdesign-vue-next')['Loading']
    TMenu: typeof import('tdesign-vue-next')['Menu']
    TMenuGroup: typeof import('tdesign-vue-next')['MenuGroup']
    TMenuItem: typeof import('tdesign-vue-next')['MenuItem']
    TRadioButton: typeof import('tdesign-vue-next')['RadioButton']
    TRadioGroup: typeof import('tdesign-vue-next')['RadioGroup']
    TSelect: typeof import('tdesign-vue-next')['Select']
    TSkeleton: typeof import('tdesign-vue-next')['Skeleton']
    TSpace: typeof import('tdesign-vue-next')['Space']
    TSubmenu: typeof import('tdesign-vue-next')['Submenu']
    TSwitch: typeof import('tdesign-vue-next')['Switch']
    TTabPanel: typeof import('tdesign-vue-next')['TabPanel']
    TTabs: typeof import('tdesign-vue-next')['Tabs']
    TTag: typeof import('tdesign-vue-next')['Tag']
    TTextarea: typeof import('tdesign-vue-next')['Textarea']
    UtoolsImage: typeof import('./src/components/UtoolsImage/UtoolsImage.vue')['default']
  }
}
