// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as services$0 from "../../../../../dsh-plugin-manager/services/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "proc:exit": services$0.ProcExit;
            "proc:output": services$0.ProcOutput;
            "tray:quit-ready": void;
            "tray:quit-request": void;
            "tray:service-status": services$0.TrayServiceStatus;
            "tray:toggle-service": void;
        }
    }
}
