// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BrowserService 内置浏览器窗口管理（单例复用）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * OpenInBuiltin 在内置浏览器窗口中打开 url；窗口已存在则按需更新地址并聚焦复用。
 */
export function OpenInBuiltin(url: string, width: number, height: number): $CancellablePromise<void> {
    return $Call.ByID(855734028, url, width, height);
}
