// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DshService dsh 生态访问层。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * * $DSH_HOME：显式配置 > $DSH_HOME 环境变量 > ~/.dsh
 */
export function GetDshHome(): $CancellablePromise<string> {
    return $Call.ByID(4231135373);
}

/**
 * * 列出所有 profile（目录下存在 package.json 视为一个 profile）。
 */
export function ListProfiles(): $CancellablePromise<string[] | null> {
    return $Call.ByID(910159059);
}

/**
 * * 读取 bundle 自带 patch（dsh.bundle.patch 指向的文件）原文；无则返回 nil。
 */
export function ReadBundlePatch(profile: string, packageName: string): $CancellablePromise<string | null> {
    return $Call.ByID(1266019945, profile, packageName);
}

/**
 * * 读取已安装包（bundle 或普通依赖）的 package.json；未安装返回 nil。
 */
export function ReadInstalledPackage(profile: string, packageName: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(1815904319, profile, packageName);
}

/**
 * * 读取 profile 的 package.json；不存在或解析失败返回 nil。
 */
export function ReadProfileManifest(profile: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(1046493031, profile);
}

/**
 * * 读取 profile 级 cordis.patch.yml 原文；不存在时返回空串。
 */
export function ReadProfilePatch(profile: string): $CancellablePromise<string> {
    return $Call.ByID(166988580, profile);
}

/**
 * * 解析并探测 dsh：手动配置 > PATH > ~/.bun/bin，随后探测运行方式。
 */
export function ResolveDsh(configuredPath: string): $CancellablePromise<$models.DshResolveResult> {
    return $Call.ByID(3207184766, configuredPath);
}

/**
 * * 解析 dsh 可执行文件：手动配置 > PATH > ~/.bun/bin（bun 全局安装目录）。
 */
export function ResolveDshBin(configuredPath: string): $CancellablePromise<string | null> {
    return $Call.ByID(2389257323, configuredPath);
}

/**
 * * 解析 bun / npm 等全局工具可执行文件：bun 额外兜底 ~/.bun/bin（默认安装目录），其余仅在 PATH 查找。未找到返回 nil。
 */
export function ResolveToolBin(name: string): $CancellablePromise<string | null> {
    return $Call.ByID(3902555958, name);
}

export function WriteProfileManifest(profile: string, manifest: { [_ in string]?: any } | null): $CancellablePromise<void> {
    return $Call.ByID(3150016832, profile, manifest);
}

export function WriteProfilePatch(profile: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(1055554381, profile, content);
}
