// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileService 通用文件读写。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

export function ReadTextFile(path: string): $CancellablePromise<string> {
    return $Call.ByID(327323639, path);
}

export function WriteTextFile(path: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(1324542752, path, content);
}
