// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as DshService from "./dshservice.js";
import * as KVService from "./kvservice.js";
import * as ProcService from "./procservice.js";
export {
    DshService,
    KVService,
    ProcService
};

export type {
    DshResolveResult,
    ProcExit,
    ProcOutput,
    TrayServiceStatus
} from "./models.js";
