// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * KVService 键值存储。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

export function GetItem(key: string): $CancellablePromise<any> {
    return $Call.ByID(2701634172, key);
}

export function RemoveItem(key: string): $CancellablePromise<void> {
    return $Call.ByID(2906465058, key);
}

export function SetItem(key: string, value: any): $CancellablePromise<void> {
    return $Call.ByID(1299822632, key, value);
}
