// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DshResolveResult dsh 可执行文件解析结果（state: ok | missing | invalid）。
 */
export interface DshResolveResult {
    "state": string;
    "path"?: string;
    "command"?: string;
    "prefix"?: string[] | null;
    "version"?: string;
    "error"?: string;
}

/**
 * ProcExit CLI 进程退出事件负载，经事件 "proc:exit" 推送给前端。
 */
export interface ProcExit {
    "jobId": string;
    "code": number;
}

/**
 * ProcOutput CLI 流式输出事件负载，经事件 "proc:output" 推送给前端。
 */
export interface ProcOutput {
    "jobId": string;

    /**
     * stdout | stderr
     */
    "stream": string;
    "text": string;
}
