// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DshResolveResult dsh 可执行文件解析结果（state: ok | missing | invalid）。
 */
export interface DshResolveResult {
    "state": string;
    "path"?: string;
    "command"?: string;
    "prefix"?: string[] | null;
    "version"?: string;
    "error"?: string;
}

/**
 * ProcExit CLI 进程退出事件负载，经事件 "proc:exit" 推送给前端。
 */
export interface ProcExit {
    "jobId": string;
    "code": number;
}

/**
 * ProcOutput CLI 流式输出事件负载，经事件 "proc:output" 推送给前端。
 */
export interface ProcOutput {
    "jobId": string;

    /**
     * stdout | stderr
     */
    "stream": string;
    "text": string;
}

/**
 * TrayServiceStatus 托盘"启动/停止服务"菜单项状态，经事件 "tray:service-status" 由前端推送给 Go。
 * Running 表示当前 profile 的 web 服务是否在运行（本管理器启动或外部启动均可）；
 * Supported 表示当前 profile 是否包含 dsh web 应用，不含时菜单项置灰。
 */
export interface TrayServiceStatus {
    "running": boolean;
    "supported": boolean;
}
