// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProcService 进程与端口工具。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * * 通过 lsof（darwin/linux）找到监听某端口的 PID；win32 不支持返回 nil。
 */
export function FindPidByPort(port: number): $CancellablePromise<number | null> {
    return $Call.ByID(3435341158, port);
}

/**
 * * PID 是否存活。
 */
export function IsAlive(pid: number): $CancellablePromise<boolean> {
    return $Call.ByID(2817533285, pid);
}

/**
 * * 杀进程：SIGTERM 后等待退出，3s 内未退出则 SIGKILL 兜底。
 */
export function Kill(pid: number): $CancellablePromise<boolean> {
    return $Call.ByID(3541774748, pid);
}

/**
 * *
 *  * 流式启动子进程（dsh CLI / web 服务）。
 *  * 输出经事件 "proc:output" 推送，进程退出后经 "proc:exit" 推送；
 *  * detached 时子进程脱离本进程组（父进程退出后继续运行）。
 *  * 立即返回子进程 pid，启动失败返回 -1。
 */
export function RunCli(jobId: string, cmd: string, args: string[] | null, detached: boolean): $CancellablePromise<number> {
    return $Call.ByID(2053251597, jobId, cmd, args, detached);
}
